version: '3'

dotenv:
- Taskfile.env

includes:
  constructor:
    taskfile: .constructor/Taskfile.yml
    dir: .constructor
    optional: true

  provisioner:
    taskfile: .provisioner/Taskfile.yml
    dir: .provisioner
    optional: true

tasks:
  default:
    silent: true
    cmds:
    - task --list

  _git_clone_if_not_exist:
    internal: true
    vars:
      REPO_URL: '{{.REPO_URL}}'
      REPO_BRANCH: '{{.REPO_BRANCH}}'
      REPO_DIR: '{{.REPO_DIR}}'
    status:
    - test -d "{{.REPO_DIR}}"
    cmds:
    - git clone --progress
                --verbose
                --single-branch
                --branch '{{.REPO_BRANCH}}'
                '{{.REPO_URL}}'
                '{{.REPO_DIR}}'

  _git_checkout_or_pull:
    internal: true
    deps:
    - task: _git_clone_if_not_exist
      vars:
        REPO_URL: '{{.REPO_URL}}'
        REPO_BRANCH: '{{.REPO_BRANCH}}'
        REPO_DIR: '{{.REPO_DIR}}'
    vars:
      REPO_DIR: '{{.REPO_DIR}}'
      REPO_TAG: '{{.REPO_TAG}}'
    cmds:
    - cd '{{.REPO_DIR}}' &&
      {{if eq .REPO_TAG ""}}
        git pull
      {{else}}
        git checkout tags/{{.REPO_TAG}}
      {{end}}

  checkout-or-pull:
    desc: Git checkout or pull the constructor and provisioner repositories
    aliases:
    - cop
    deps:
    - cop-constructor
    - cop-privisioner

  checkout-or-pull-constructor:
    desc: Git checkout or pull the constructor repository
    aliases:
    - cop-constructor
    - cop-c
    deps:
    - task: _git_checkout_or_pull
      vars:
        REPO_URL: '{{.CONSTRUCTOR_REPO_URL}}'
        REPO_BRANCH: '{{.CONSTRUCTOR_REPO_BRANCH}}'
        REPO_TAG: '{{.CONSTRUCTOR_REPO_TAG}}'
        REPO_DIR: '{{.CONSTRUCTOR_REPO_DIR}}'

  checkout-or-pull-provisioner:
    desc: Git checkout or pull the provisioner repository
    aliases:
    - cop-provisioner
    - cop-p
    deps:
    - task: _git_checkout_or_pull
      vars:
        REPO_URL: '{{.PROVISIONER_REPO_URL}}'
        REPO_BRANCH: '{{.PROVISIONER_REPO_BRANCH}}'
        REPO_TAG: '{{.PROVISIONER_REPO_TAG}}'
        REPO_DIR: '{{.PROVISIONER_REPO_DIR}}'